### PR TITLE
adding sound effects

### PR DESCRIPTION
**Pull request by sumit2011**

### CODE REVIEW

**Comment by sumit2011** [comment]
@vikram-kangotra bro merge this commit i just added the gameover sound.

**Comment by vikram-kangotra** [comment]
That's amazing! Thanks for the Pull Request :)

I am also working on merging [this PR](https://github.com/vikram-kangotra/Dino/pull/6).
But the sounds do not match then. 
I would request you to change the audio file (should match the sounds used in the PR mentioned above)

Also, keep the audio files in the [assets](https://github.com/vikram-kangotra/Dino/tree/main/assets) folder

**Comment by sumit2011** [comment]
Now check this...

**Comment by vikram-kangotra** [comment]
Thanks for your work :)
But I can't accept the merge because the issue was resolved in [the PR](https://github.com/vikram-kangotra/Dino/pull/6) I mentioned above.

You can look at solving other issues in the game or check out my other repos though.

**Pull request closed without merging**
